name: rsqsim-python-tools
channels:
  - conda-forge
dependencies:
  - python
  - pyproj
  - numpy
  - numba
  - geopandas
  - jupyter
  - matplotlib
  - netcdf4
  - ipython
  - scipy
  - rasterio
  - h5py
  - pytables
  - ffmpeg
  - xlrd
  - rioxarray
  - pip
  - git
  - git-lfs
  - pip:
    - src/rsqsim_api
    - src/tri_dislocations
    - ezdxf
    - meshio
