name: rnc2
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy >= 1.18.1
  - numba >= 0.51.2
  - geopandas >= 0.6.1
  - ipyvolume >= 0.5.2
  - jupyter_client >= 6.1.7
  - matplotlib >= 3.1.1
  - netcdf4 >= 1.4.2
  - ipython >= 7.9.0
  - scipy >= 1.3.1
  - rasterio >= 1.1.0
  - h5py >= 2.10.0
  - pytables >= 3.6.1
  - ffmpeg >= 4.3.1
  - xlrd >= 2.0.1
  - pip
  - pip:
    - src/rsqsim_api
    - src/tri_dislocations
    - src/triangular_faults
    - ezdxf >= 0.14.2
