name: rsqsim-python-tools
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pyproj
  - numpy
  - numba
  - geopandas
  - jupyter
  - matplotlib
  - netcdf4
  - ipython
  - scipy
  - rasterio
  - h5py
  - pytables
  - ffmpeg
  - xlrd
  - rioxarray
  - pip
  - git
  - git-lfs
  - sphinx
  - sphinx-autoapi
  - pip:
    - src/rsqsim_api
    - ezdxf
    - meshio
    - sphinx-rtd-theme
